sudo: false
language: node_js
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  directories:
    - ~/.cache
    - ~/.cache
notifications:
  email: false
node_js: '20'
install: echo "install happens as part of setup"
script: npm run setup
after_script: npx codecov@3
branches:
  only: [master]
